kind: Deployment
apiVersion: apps/v1
metadata:
  name: paas-front
  labels:
    app: paas-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paas-front
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: paas-front
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: paas-front
          env:        
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: paas-front
                  key: PORT
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext: {}
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/paas-front:latest
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600