apiVersion: v1
kind: Service
metadata:
  name: paas-front
  labels:
    app: paas-front
spec:
  selector:
    app: paas-front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 8080-tcp